server:
  port: 8080

spring:
  application:
    name: backend-service
  profiles:
    active: @spring.profiles.active@
  spring:
    servlet:
      multipart:
        max-file-size: 50MB       # default = 1MB
        max-request-size: 50MB    # default = 10MB (form data)
security:
  authentication:
    jwt:
      base64-secret: ODcxODJlOGI4YTdhZWNlYzE4NmRhNzQwYzQ4ZmIxOTQzODMzZDcxOWQ2OGVlNTk5MjY0MTcxNTc3YTcyZmIzN2I0YmI4NmI1ZDU2NDU4YzUxZjI0MDMwM2E5MDI4YWU5YTIyMWQ5ZDNhODBhMmNhZjFkM2VlZWRhN2Y4ZWVlOTk=
      token-validity-in-seconds: 86400
api:
  prefix: /api/v1
foodapp:
  upload-file:
    base-path: file:///D:/BackendFoodApp/uploads/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#logging:
#  level:
#    root: INFO
#    web: INFO