server:
  port: 8081

spring:
  application:
    name: backend-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: td13052004@gmail.com
    password: jinp vcbu zdsn uasr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  profiles:
    active: @spring.profiles.active@
  spring:
    servlet:
      multipart:
        max-file-size: 50MB       # default = 1MB
        max-request-size: 50MB    # default = 10MB (form data)
security:
  authentication:
    jwt:
      base64-secret: ODcxODJlOGI4YTdhZWNlYzE4NmRhNzQwYzQ4ZmIxOTQzODMzZDcxOWQ2OGVlNTk5MjY0MTcxNTc3YTcyZmIzN2I0YmI4NmI1ZDU2NDU4YzUxZjI0MDMwM2E5MDI4YWU5YTIyMWQ5ZDNhODBhMmNhZjFkM2VlZWRhN2Y4ZWVlOTk=
      access-token-validity-in-seconds: 300
      refresh-token-validity-in-seconds: 604800
api:
  prefix: /api/v1
foodapp:
  upload-file:
    base-path: file:///D:/Projects/Mobile_FoodStore/Backend-AppFood/uploads/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#logging:
#  level:
#    root: INFO
#    web: INFO